// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbtMdwcQ-VFA7q4J2wh3y1RfmlQmlrSU',
    appId: '1:688460802866:web:48fb853f9b5cc4fb3f852b',
    messagingSenderId: '688460802866',
    projectId: 'sp27rednewapp',
    authDomain: 'sp27rednewapp.firebaseapp.com',
    storageBucket: 'sp27rednewapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOURLoOfvgwMro2pGfCAsIzv5_oLCC1eU',
    appId: '1:688460802866:android:23aaac254a431ee83f852b',
    messagingSenderId: '688460802866',
    projectId: 'sp27rednewapp',
    storageBucket: 'sp27rednewapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFc8bSf6GT9yPCdm_26E-LwrBSW5PK48',
    appId: '1:688460802866:ios:a5b99a3a05f4c7dc3f852b',
    messagingSenderId: '688460802866',
    projectId: 'sp27rednewapp',
    storageBucket: 'sp27rednewapp.firebasestorage.app',
    iosBundleId: 'com.example.spotifyRedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFc8bSf6GT9yPCdm_26E-LwrBSW5PK48',
    appId: '1:688460802866:ios:a5b99a3a05f4c7dc3f852b',
    messagingSenderId: '688460802866',
    projectId: 'sp27rednewapp',
    storageBucket: 'sp27rednewapp.firebasestorage.app',
    iosBundleId: 'com.example.spotifyRedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtbtMdwcQ-VFA7q4J2wh3y1RfmlQmlrSU',
    appId: '1:688460802866:web:d3d1b8dfe9e047cd3f852b',
    messagingSenderId: '688460802866',
    projectId: 'sp27rednewapp',
    authDomain: 'sp27rednewapp.firebaseapp.com',
    storageBucket: 'sp27rednewapp.firebasestorage.app',
  );
}
